// Code generated by protoc-gen-gogo.
// source: protos/workerp/payload.proto
// DO NOT EDIT!

/*
	Package workerp is a generated protocol buffer package.

	It is generated from these files:
		protos/workerp/payload.proto

	It has these top-level messages:
		Payload
		BackupPayload
		ClusterConfChange
*/
package workerp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import taskp "github.com/dgraph-io/dgraph/protos/taskp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BackupPayload_Status int32

const (
	BackupPayload_NONE      BackupPayload_Status = 0
	BackupPayload_SUCCESS   BackupPayload_Status = 1
	BackupPayload_DUPLICATE BackupPayload_Status = 2
	BackupPayload_FAILED    BackupPayload_Status = 3
)

var BackupPayload_Status_name = map[int32]string{
	0: "NONE",
	1: "SUCCESS",
	2: "DUPLICATE",
	3: "FAILED",
}
var BackupPayload_Status_value = map[string]int32{
	"NONE":      0,
	"SUCCESS":   1,
	"DUPLICATE": 2,
	"FAILED":    3,
}

func (x BackupPayload_Status) String() string {
	return proto.EnumName(BackupPayload_Status_name, int32(x))
}
func (BackupPayload_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorPayload, []int{1, 0}
}

type ClusterConfChange_Op int32

const (
	ClusterConfChange_ADD    ClusterConfChange_Op = 0
	ClusterConfChange_REMOVE ClusterConfChange_Op = 1
	ClusterConfChange_JOIN   ClusterConfChange_Op = 2
)

var ClusterConfChange_Op_name = map[int32]string{
	0: "ADD",
	1: "REMOVE",
	2: "JOIN",
}
var ClusterConfChange_Op_value = map[string]int32{
	"ADD":    0,
	"REMOVE": 1,
	"JOIN":   2,
}

func (x ClusterConfChange_Op) String() string {
	return proto.EnumName(ClusterConfChange_Op_name, int32(x))
}
func (ClusterConfChange_Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorPayload, []int{2, 0}
}

type Payload struct {
	Data []byte `protobuf:"bytes,1,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptorPayload, []int{0} }

func (m *Payload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// BackupPayload is used both as a request and a response.
// When used in request, groups represents the list of groups that need to be backed up.
// When used in response, groups represent the list of groups that were backed up.
type BackupPayload struct {
	ReqId   uint64               `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	GroupId uint32               `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Status  BackupPayload_Status `protobuf:"varint,3,opt,name=status,proto3,enum=workerp.BackupPayload_Status" json:"status,omitempty"`
}

func (m *BackupPayload) Reset()                    { *m = BackupPayload{} }
func (m *BackupPayload) String() string            { return proto.CompactTextString(m) }
func (*BackupPayload) ProtoMessage()               {}
func (*BackupPayload) Descriptor() ([]byte, []int) { return fileDescriptorPayload, []int{1} }

func (m *BackupPayload) GetReqId() uint64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *BackupPayload) GetGroupId() uint32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *BackupPayload) GetStatus() BackupPayload_Status {
	if m != nil {
		return m.Status
	}
	return BackupPayload_NONE
}

type ClusterConfChange struct {
	Context *taskp.RaftContext   `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Op      ClusterConfChange_Op `protobuf:"varint,2,opt,name=op,proto3,enum=workerp.ClusterConfChange_Op" json:"op,omitempty"`
}

func (m *ClusterConfChange) Reset()                    { *m = ClusterConfChange{} }
func (m *ClusterConfChange) String() string            { return proto.CompactTextString(m) }
func (*ClusterConfChange) ProtoMessage()               {}
func (*ClusterConfChange) Descriptor() ([]byte, []int) { return fileDescriptorPayload, []int{2} }

func (m *ClusterConfChange) GetContext() *taskp.RaftContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *ClusterConfChange) GetOp() ClusterConfChange_Op {
	if m != nil {
		return m.Op
	}
	return ClusterConfChange_ADD
}

func init() {
	proto.RegisterType((*Payload)(nil), "workerp.Payload")
	proto.RegisterType((*BackupPayload)(nil), "workerp.BackupPayload")
	proto.RegisterType((*ClusterConfChange)(nil), "workerp.ClusterConfChange")
	proto.RegisterEnum("workerp.BackupPayload_Status", BackupPayload_Status_name, BackupPayload_Status_value)
	proto.RegisterEnum("workerp.ClusterConfChange_Op", ClusterConfChange_Op_name, ClusterConfChange_Op_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Worker service

type WorkerClient interface {
	// Connection testing RPC.
	Echo(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error)
	// Data serving RPCs.
	AssignUids(ctx context.Context, in *taskp.Num, opts ...grpc.CallOption) (*taskp.List, error)
	Mutate(ctx context.Context, in *taskp.Mutations, opts ...grpc.CallOption) (*Payload, error)
	ServeTask(ctx context.Context, in *taskp.Query, opts ...grpc.CallOption) (*taskp.Result, error)
	PredicateAndSchemaData(ctx context.Context, opts ...grpc.CallOption) (Worker_PredicateAndSchemaDataClient, error)
	Sort(ctx context.Context, in *taskp.Sort, opts ...grpc.CallOption) (*taskp.SortResult, error)
	RebuildIndex(ctx context.Context, in *taskp.RebuildIndex, opts ...grpc.CallOption) (*Payload, error)
	Schema(ctx context.Context, in *taskp.Schema, opts ...grpc.CallOption) (*taskp.SchemaResult, error)
	// RAFT serving RPCs.
	RaftMessage(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error)
	UpdateMembership(ctx context.Context, in *taskp.MembershipUpdate, opts ...grpc.CallOption) (*taskp.MembershipUpdate, error)
	Backup(ctx context.Context, in *BackupPayload, opts ...grpc.CallOption) (*BackupPayload, error)
	ManageCluster(ctx context.Context, in *ClusterConfChange, opts ...grpc.CallOption) (*Payload, error)
}

type workerClient struct {
	cc *grpc.ClientConn
}

func NewWorkerClient(cc *grpc.ClientConn) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) Echo(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error) {
	out := new(Payload)
	err := grpc.Invoke(ctx, "/workerp.Worker/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) AssignUids(ctx context.Context, in *taskp.Num, opts ...grpc.CallOption) (*taskp.List, error) {
	out := new(taskp.List)
	err := grpc.Invoke(ctx, "/workerp.Worker/AssignUids", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) Mutate(ctx context.Context, in *taskp.Mutations, opts ...grpc.CallOption) (*Payload, error) {
	out := new(Payload)
	err := grpc.Invoke(ctx, "/workerp.Worker/Mutate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) ServeTask(ctx context.Context, in *taskp.Query, opts ...grpc.CallOption) (*taskp.Result, error) {
	out := new(taskp.Result)
	err := grpc.Invoke(ctx, "/workerp.Worker/ServeTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) PredicateAndSchemaData(ctx context.Context, opts ...grpc.CallOption) (Worker_PredicateAndSchemaDataClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Worker_serviceDesc.Streams[0], c.cc, "/workerp.Worker/PredicateAndSchemaData", opts...)
	if err != nil {
		return nil, err
	}
	x := &workerPredicateAndSchemaDataClient{stream}
	return x, nil
}

type Worker_PredicateAndSchemaDataClient interface {
	Send(*taskp.GroupKeys) error
	Recv() (*taskp.KV, error)
	grpc.ClientStream
}

type workerPredicateAndSchemaDataClient struct {
	grpc.ClientStream
}

func (x *workerPredicateAndSchemaDataClient) Send(m *taskp.GroupKeys) error {
	return x.ClientStream.SendMsg(m)
}

func (x *workerPredicateAndSchemaDataClient) Recv() (*taskp.KV, error) {
	m := new(taskp.KV)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workerClient) Sort(ctx context.Context, in *taskp.Sort, opts ...grpc.CallOption) (*taskp.SortResult, error) {
	out := new(taskp.SortResult)
	err := grpc.Invoke(ctx, "/workerp.Worker/Sort", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) RebuildIndex(ctx context.Context, in *taskp.RebuildIndex, opts ...grpc.CallOption) (*Payload, error) {
	out := new(Payload)
	err := grpc.Invoke(ctx, "/workerp.Worker/RebuildIndex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) Schema(ctx context.Context, in *taskp.Schema, opts ...grpc.CallOption) (*taskp.SchemaResult, error) {
	out := new(taskp.SchemaResult)
	err := grpc.Invoke(ctx, "/workerp.Worker/Schema", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) RaftMessage(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Payload, error) {
	out := new(Payload)
	err := grpc.Invoke(ctx, "/workerp.Worker/RaftMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) UpdateMembership(ctx context.Context, in *taskp.MembershipUpdate, opts ...grpc.CallOption) (*taskp.MembershipUpdate, error) {
	out := new(taskp.MembershipUpdate)
	err := grpc.Invoke(ctx, "/workerp.Worker/UpdateMembership", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) Backup(ctx context.Context, in *BackupPayload, opts ...grpc.CallOption) (*BackupPayload, error) {
	out := new(BackupPayload)
	err := grpc.Invoke(ctx, "/workerp.Worker/Backup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) ManageCluster(ctx context.Context, in *ClusterConfChange, opts ...grpc.CallOption) (*Payload, error) {
	out := new(Payload)
	err := grpc.Invoke(ctx, "/workerp.Worker/ManageCluster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Worker service

type WorkerServer interface {
	// Connection testing RPC.
	Echo(context.Context, *Payload) (*Payload, error)
	// Data serving RPCs.
	AssignUids(context.Context, *taskp.Num) (*taskp.List, error)
	Mutate(context.Context, *taskp.Mutations) (*Payload, error)
	ServeTask(context.Context, *taskp.Query) (*taskp.Result, error)
	PredicateAndSchemaData(Worker_PredicateAndSchemaDataServer) error
	Sort(context.Context, *taskp.Sort) (*taskp.SortResult, error)
	RebuildIndex(context.Context, *taskp.RebuildIndex) (*Payload, error)
	Schema(context.Context, *taskp.Schema) (*taskp.SchemaResult, error)
	// RAFT serving RPCs.
	RaftMessage(context.Context, *Payload) (*Payload, error)
	UpdateMembership(context.Context, *taskp.MembershipUpdate) (*taskp.MembershipUpdate, error)
	Backup(context.Context, *BackupPayload) (*BackupPayload, error)
	ManageCluster(context.Context, *ClusterConfChange) (*Payload, error)
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Payload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workerp.Worker/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Echo(ctx, req.(*Payload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_AssignUids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(taskp.Num)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).AssignUids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workerp.Worker/AssignUids",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).AssignUids(ctx, req.(*taskp.Num))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_Mutate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(taskp.Mutations)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Mutate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workerp.Worker/Mutate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Mutate(ctx, req.(*taskp.Mutations))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_ServeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(taskp.Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).ServeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workerp.Worker/ServeTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).ServeTask(ctx, req.(*taskp.Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_PredicateAndSchemaData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServer).PredicateAndSchemaData(&workerPredicateAndSchemaDataServer{stream})
}

type Worker_PredicateAndSchemaDataServer interface {
	Send(*taskp.KV) error
	Recv() (*taskp.GroupKeys, error)
	grpc.ServerStream
}

type workerPredicateAndSchemaDataServer struct {
	grpc.ServerStream
}

func (x *workerPredicateAndSchemaDataServer) Send(m *taskp.KV) error {
	return x.ServerStream.SendMsg(m)
}

func (x *workerPredicateAndSchemaDataServer) Recv() (*taskp.GroupKeys, error) {
	m := new(taskp.GroupKeys)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Worker_Sort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(taskp.Sort)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Sort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workerp.Worker/Sort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Sort(ctx, req.(*taskp.Sort))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_RebuildIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(taskp.RebuildIndex)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).RebuildIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workerp.Worker/RebuildIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).RebuildIndex(ctx, req.(*taskp.RebuildIndex))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_Schema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(taskp.Schema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Schema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workerp.Worker/Schema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Schema(ctx, req.(*taskp.Schema))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_RaftMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Payload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).RaftMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workerp.Worker/RaftMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).RaftMessage(ctx, req.(*Payload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_UpdateMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(taskp.MembershipUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).UpdateMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workerp.Worker/UpdateMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).UpdateMembership(ctx, req.(*taskp.MembershipUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workerp.Worker/Backup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Backup(ctx, req.(*BackupPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_ManageCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterConfChange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).ManageCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workerp.Worker/ManageCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).ManageCluster(ctx, req.(*ClusterConfChange))
	}
	return interceptor(ctx, in, info, handler)
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "workerp.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Worker_Echo_Handler,
		},
		{
			MethodName: "AssignUids",
			Handler:    _Worker_AssignUids_Handler,
		},
		{
			MethodName: "Mutate",
			Handler:    _Worker_Mutate_Handler,
		},
		{
			MethodName: "ServeTask",
			Handler:    _Worker_ServeTask_Handler,
		},
		{
			MethodName: "Sort",
			Handler:    _Worker_Sort_Handler,
		},
		{
			MethodName: "RebuildIndex",
			Handler:    _Worker_RebuildIndex_Handler,
		},
		{
			MethodName: "Schema",
			Handler:    _Worker_Schema_Handler,
		},
		{
			MethodName: "RaftMessage",
			Handler:    _Worker_RaftMessage_Handler,
		},
		{
			MethodName: "UpdateMembership",
			Handler:    _Worker_UpdateMembership_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _Worker_Backup_Handler,
		},
		{
			MethodName: "ManageCluster",
			Handler:    _Worker_ManageCluster_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PredicateAndSchemaData",
			Handler:       _Worker_PredicateAndSchemaData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/workerp/payload.proto",
}

func (m *Payload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Payload) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPayload(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func (m *BackupPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BackupPayload) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ReqId != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPayload(dAtA, i, uint64(m.ReqId))
	}
	if m.GroupId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintPayload(dAtA, i, uint64(m.GroupId))
	}
	if m.Status != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintPayload(dAtA, i, uint64(m.Status))
	}
	return i, nil
}

func (m *ClusterConfChange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterConfChange) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Context != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPayload(dAtA, i, uint64(m.Context.Size()))
		n1, err := m.Context.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Op != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintPayload(dAtA, i, uint64(m.Op))
	}
	return i, nil
}

func encodeFixed64Payload(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Payload(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintPayload(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Payload) Size() (n int) {
	var l int
	_ = l
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovPayload(uint64(l))
	}
	return n
}

func (m *BackupPayload) Size() (n int) {
	var l int
	_ = l
	if m.ReqId != 0 {
		n += 1 + sovPayload(uint64(m.ReqId))
	}
	if m.GroupId != 0 {
		n += 1 + sovPayload(uint64(m.GroupId))
	}
	if m.Status != 0 {
		n += 1 + sovPayload(uint64(m.Status))
	}
	return n
}

func (m *ClusterConfChange) Size() (n int) {
	var l int
	_ = l
	if m.Context != nil {
		l = m.Context.Size()
		n += 1 + l + sovPayload(uint64(l))
	}
	if m.Op != 0 {
		n += 1 + sovPayload(uint64(m.Op))
	}
	return n
}

func sovPayload(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozPayload(x uint64) (n int) {
	return sovPayload(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Payload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPayload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Payload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Payload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPayload
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPayload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPayload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BackupPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPayload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BackupPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BackupPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReqId", wireType)
			}
			m.ReqId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReqId |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupId", wireType)
			}
			m.GroupId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroupId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (BackupPayload_Status(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPayload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPayload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterConfChange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPayload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterConfChange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterConfChange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Context", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPayload
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Context == nil {
				m.Context = &taskp.RaftContext{}
			}
			if err := m.Context.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Op", wireType)
			}
			m.Op = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Op |= (ClusterConfChange_Op(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPayload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPayload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPayload(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPayload
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPayload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthPayload
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPayload
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPayload(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPayload = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPayload   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("protos/workerp/payload.proto", fileDescriptorPayload) }

var fileDescriptorPayload = []byte{
	// 636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x4e, 0xdb, 0x4c,
	0x14, 0xb5, 0x43, 0x70, 0xe0, 0x86, 0x7c, 0x32, 0x17, 0x7d, 0x94, 0x5a, 0x25, 0x42, 0xee, 0x43,
	0xa3, 0x0a, 0x9c, 0x0a, 0x54, 0x55, 0xa2, 0x0f, 0x55, 0x70, 0x4c, 0x95, 0x42, 0x12, 0x6a, 0x13,
	0xfa, 0x58, 0x4d, 0xe2, 0xc1, 0xb1, 0x92, 0x78, 0x8c, 0x67, 0xdc, 0xc2, 0x02, 0xba, 0x84, 0x4a,
	0x5d, 0x48, 0x17, 0xd1, 0xc7, 0x2e, 0xa1, 0xa2, 0x1b, 0xa9, 0xfc, 0x93, 0x14, 0x44, 0x22, 0xf5,
	0x25, 0x9a, 0x73, 0xee, 0x99, 0x33, 0x67, 0xee, 0xdc, 0x18, 0x9e, 0x84, 0x11, 0x13, 0x8c, 0xd7,
	0x3f, 0xb3, 0x68, 0x44, 0xa3, 0xb0, 0x1e, 0x92, 0x9b, 0x31, 0x23, 0xae, 0x91, 0xd2, 0x58, 0xca,
	0x69, 0xed, 0xc0, 0xf3, 0xc5, 0x30, 0xee, 0x1b, 0x03, 0x36, 0xa9, 0xbb, 0x5e, 0x44, 0xc2, 0xe1,
	0x9e, 0xcf, 0xf2, 0x55, 0x3d, 0xb7, 0x10, 0x84, 0x8f, 0xc2, 0xf4, 0x37, 0xdb, 0xad, 0x6f, 0x43,
	0xe9, 0x2c, 0xb3, 0x43, 0x84, 0x62, 0x93, 0x08, 0xb2, 0x25, 0xef, 0xc8, 0xb5, 0x35, 0xbb, 0xe8,
	0x12, 0x41, 0xf4, 0xef, 0x32, 0x54, 0x8e, 0xc8, 0x60, 0x14, 0x87, 0x53, 0xd5, 0xff, 0xa0, 0x44,
	0xf4, 0xea, 0xa3, 0xef, 0xa6, 0xba, 0xa2, 0xbd, 0x1c, 0xd1, 0xab, 0x96, 0x8b, 0x8f, 0x61, 0xc5,
	0x8b, 0x58, 0x1c, 0x26, 0x85, 0xc2, 0x8e, 0x5c, 0xab, 0xd8, 0xa5, 0x14, 0xb7, 0x5c, 0x7c, 0x09,
	0x0a, 0x17, 0x44, 0xc4, 0x7c, 0x6b, 0x69, 0x47, 0xae, 0xfd, 0xb7, 0xbf, 0x6d, 0xe4, 0x89, 0x8d,
	0x7b, 0xce, 0x86, 0x93, 0x8a, 0xec, 0x5c, 0xac, 0x1f, 0x82, 0x92, 0x31, 0xb8, 0x02, 0xc5, 0x4e,
	0xb7, 0x63, 0xa9, 0x12, 0x96, 0xa1, 0xe4, 0xf4, 0x4c, 0xd3, 0x72, 0x1c, 0x55, 0xc6, 0x0a, 0xac,
	0x36, 0x7b, 0x67, 0xa7, 0x2d, 0xb3, 0x71, 0x6e, 0xa9, 0x05, 0x04, 0x50, 0x8e, 0x1b, 0xad, 0x53,
	0xab, 0xa9, 0x2e, 0xe9, 0x5f, 0x65, 0x58, 0x37, 0xc7, 0x31, 0x17, 0x34, 0x32, 0x59, 0x70, 0x69,
	0x0e, 0x49, 0xe0, 0x51, 0xdc, 0x85, 0xd2, 0x80, 0x05, 0x82, 0x5e, 0x8b, 0x34, 0x7b, 0x79, 0x1f,
	0x8d, 0xb4, 0x1f, 0x86, 0x4d, 0x2e, 0x85, 0x99, 0x55, 0xec, 0xa9, 0x04, 0xf7, 0xa0, 0xc0, 0xc2,
	0xf4, 0x2e, 0x77, 0x23, 0x3f, 0x70, 0x35, 0xba, 0xa1, 0x5d, 0x60, 0xa1, 0xfe, 0x14, 0x0a, 0xdd,
	0x10, 0x4b, 0xb0, 0xd4, 0x68, 0x36, 0x55, 0x29, 0x49, 0x63, 0x5b, 0xed, 0xee, 0x85, 0xa5, 0xca,
	0x49, 0xfe, 0x77, 0xdd, 0x56, 0x47, 0x2d, 0xec, 0x7f, 0x59, 0x06, 0xe5, 0x43, 0xea, 0x84, 0xbb,
	0x50, 0xb4, 0x06, 0x43, 0x86, 0xea, 0xcc, 0x3a, 0xef, 0x83, 0xf6, 0x80, 0xd1, 0x25, 0x7c, 0x06,
	0xd0, 0xe0, 0xdc, 0xf7, 0x82, 0x9e, 0xef, 0x72, 0x84, 0x3c, 0x77, 0x27, 0x9e, 0x68, 0xe5, 0x7c,
	0x7d, 0xea, 0x73, 0xa1, 0x4b, 0x68, 0x80, 0xd2, 0x8e, 0x05, 0x11, 0x14, 0xd5, 0xbc, 0x90, 0x42,
	0x9f, 0x05, 0x7c, 0xae, 0xf1, 0x73, 0x58, 0x75, 0x68, 0xf4, 0x89, 0x9e, 0x13, 0x3e, 0xc2, 0xb5,
	0x7c, 0xcb, 0xfb, 0x98, 0x46, 0x37, 0x5a, 0x65, 0xda, 0x1d, 0xca, 0xe3, 0x71, 0xe2, 0xfd, 0x1a,
	0x36, 0xcf, 0x22, 0xea, 0xfa, 0x03, 0x22, 0x68, 0x23, 0x70, 0x9d, 0xc1, 0x90, 0x4e, 0x48, 0x32,
	0x32, 0xb3, 0xb3, 0xde, 0x26, 0x4f, 0x7e, 0x42, 0x6f, 0xb8, 0xb6, 0x9a, 0x33, 0x27, 0x17, 0xba,
	0x54, 0x93, 0x5f, 0xc8, 0x58, 0x83, 0xa2, 0xc3, 0x22, 0x81, 0xd3, 0xbc, 0x09, 0xd0, 0xd6, 0xef,
	0x80, 0xd9, 0x31, 0xaf, 0x60, 0xcd, 0xa6, 0xfd, 0xd8, 0x1f, 0xbb, 0xad, 0xc0, 0xa5, 0xd7, 0xb8,
	0x31, 0xcb, 0xf1, 0x97, 0x9c, 0x7b, 0x17, 0x03, 0x94, 0x2c, 0x13, 0x4e, 0xa3, 0x67, 0x50, 0xdb,
	0xb8, 0x07, 0x67, 0x07, 0x1d, 0x40, 0x39, 0x79, 0xf9, 0x36, 0xe5, 0x9c, 0x78, 0xf4, 0x1f, 0x5f,
	0xe2, 0x18, 0xd4, 0x5e, 0xe8, 0x12, 0x41, 0xdb, 0x74, 0xd2, 0xa7, 0x11, 0x1f, 0xfa, 0x21, 0x3e,
	0x9a, 0xb6, 0x7a, 0x46, 0x65, 0x12, 0x6d, 0x51, 0x41, 0x97, 0xf0, 0x10, 0x94, 0x6c, 0xfc, 0x71,
	0x73, 0xfe, 0xff, 0x41, 0x5b, 0xc0, 0xeb, 0x12, 0xbe, 0x81, 0x4a, 0x9b, 0x04, 0xc4, 0xa3, 0xf9,
	0x34, 0xa2, 0xb6, 0x78, 0x3e, 0xe7, 0x5d, 0xe2, 0x48, 0xfd, 0x71, 0x5b, 0x95, 0x7f, 0xde, 0x56,
	0xe5, 0x5f, 0xb7, 0x55, 0xf9, 0xdb, 0xef, 0xaa, 0xd4, 0x57, 0xd2, 0xcf, 0xc1, 0xc1, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xa3, 0x04, 0xad, 0xcd, 0x6c, 0x04, 0x00, 0x00,
}
